FROM node:20-alpine AS builder

WORKDIR /app

COPY Frontend/package.json /app/package.json
RUN npm install

COPY Frontend /app
RUN npm run build

FROM nginx:1.27-alpine

COPY Devops/nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
