services:
  mariadb:
    image: mariadb:11.6
    container_name: govdoc-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: viet_law_rag
      MARIADB_USER: raguser
      MARIADB_PASSWORD: ragpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
